<div align='left'><font size="6" color="#FFA500">[LAB 02] Khai Thác Dữ Liệu - Sự tương đồng và các khoảng cách </font></div>

> Sinh viên: Nguyễn Công Hoài Nam <br>
  Mã số sinh viên: 21280099

### 1. Khoảng cách giữa các điểm trong dữ liệu số

In [114]:
import pandas as pd
import numpy as np

df = pd.read_csv('datasets/ionosphere.data', header=None)

df

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       25       26       27       28       29       30  \
0    0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1   -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2    0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3    0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4   -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   
..       ...  ...      ...      ...      ...      ...      ...      ...   
346 -0.04622  ... -0.04202  0.83479  0.00123  1.00000  0.12815  0.86660   
347  0.01606  ...  0.01361  0.93522  0.04925  0.93159  0.08168  0.94066   
348  0.02446  ...  0.03193  0.92489  0.02542  0.92120  0.02242  0.92459   
349  0.00110  ... -0.02099  0.89147 -0.07760  0.82983 -0.17238  0.96022   
350 -0.09139  ... -0.15114  0.81147 -0.04822  0.78207 -0.00703  0.75747   

          31       32       33  34  
0   -0.54487  0.18641 -0.45300   g  
1   -0.06288 -0.13738 -0.02447   b  
2   -0.24180  0.56045 -0.38238   g  
3    1.00000 -0.32382  1.00000   b  
4   -0.59573 -0.04608 -0.65697   g  
..       ...      ...      ...  ..  
346 -0.10714  0.90546 -0.04307   g  
347 -0.00035  0.91483  0.04712   g  
348  0.00442  0.92697 -0.00577   g  
349 -0.03757  0.87403 -0.16243   g  
350 -0.06678  0.85764 -0.06151   g  

[351 rows x 35 columns]

In [115]:
df.pop(df.columns[-1])
df

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       24       25       26       27       28       29  \
0    0.03760  ...  0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.34090   
1   -0.04549  ... -0.20332 -0.26569 -0.20468 -0.18401 -0.19040 -0.11593   
2    0.01198  ...  0.57528 -0.40220  0.58984 -0.22145  0.43100 -0.17365   
3    0.00000  ...  1.00000  0.90695  0.51613  1.00000  1.00000 -0.20099   
4   -0.16399  ...  0.03286 -0.65158  0.13290 -0.53206  0.02431 -0.62197   
..       ...  ...      ...      ...      ...      ...      ...      ...   
346 -0.04622  ...  0.95378 -0.04202  0.83479  0.00123  1.00000  0.12815   
347  0.01606  ...  0.94520  0.01361  0.93522  0.04925  0.93159  0.08168   
348  0.02446  ...  0.93988  0.03193  0.92489  0.02542  0.92120  0.02242   
349  0.00110  ...  0.91050 -0.02099  0.89147 -0.07760  0.82983 -0.17238   
350 -0.09139  ...  0.86467 -0.15114  0.81147 -0.04822  0.78207 -0.00703   

          30       31       32       33  
0    0.42267 -0.54487  0.18641 -0.45300  
1   -0.16626 -0.06288 -0.13738 -0.02447  
2    0.60436 -0.24180  0.56045 -0.38238  
3    0.25682  1.00000 -0.32382  1.00000  
4   -0.05707 -0.59573 -0.04608 -0.65697  
..       ...      ...      ...      ...  
346  0.86660 -0.10714  0.90546 -0.04307  
347  0.94066 -0.00035  0.91483  0.04712  
348  0.92459  0.00442  0.92697 -0.00577  
349  0.96022 -0.03757  0.87403 -0.16243  
350  0.75747 -0.06678  0.85764 -0.06151  

[351 rows x 34 columns]

In [116]:
array = df.values

Tính chuẩn p cho các dòng trong dữ liệu

In [117]:
def calculate_p_norms(array, p):
        
    size = len(array)
    norms = np.empty((size,size))

    for i in range(size):
        for j in range(size):
            norms[i][j] = np.linalg.norm(array[i] - array[j],p)
    
    return norms

# Gọi hàm và lấy kết quả
first_50_rows = array[:50]
p_values = [1, 2, np.inf]
for p in p_values:
    norms = calculate_p_norms(first_50_rows, p)
    print(f"Chuẩn L_{p} cho 50 dòng đầu tiên :\n", norms)
    print()


Chuẩn L_1 cho 50 dòng đầu tiên :
 [[ 0.      13.08095  5.35971 ... 15.98462  7.74504 21.06072]
 [13.08095  0.      15.80038 ... 17.53049 17.89603 18.96035]
 [ 5.35971 15.80038  0.      ... 15.88161  4.16871 19.98939]
 ...
 [15.98462 17.53049 15.88161 ...  0.      16.76954 19.93674]
 [ 7.74504 17.89603  4.16871 ... 16.76954  0.      21.72226]
 [21.06072 18.96035 19.98939 ... 19.93674 21.72226  0.     ]]

Chuẩn L_2 cho 50 dòng đầu tiên :
 [[0.         2.77635893 1.1697276  ... 3.74495828 1.59090253 4.40093478]
 [2.77635893 0.         3.38003304 ... 3.90492063 3.91433755 3.96620878]
 [1.1697276  3.38003304 0.         ... 3.82755203 0.97067099 4.35585992]
 ...
 [3.74495828 3.90492063 3.82755203 ... 0.         4.15300217 4.81090468]
 [1.59090253 3.91433755 0.97067099 ... 4.15300217 0.         4.89191224]
 [4.40093478 3.96620878 4.35585992 ... 4.81090468 4.89191224 0.        ]]

Chuẩn L_inf cho 50 dòng đầu tiên :
 [[0.      1.12221 0.45772 ... 1.85243 0.5728  1.60536]
 [1.12221 0.      1.108

### Độ đo tương đồng giữa các điểm trong tập dữ liệu categorical

In [118]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('datasets/kddcup.data.corrected', header = None)

df

0    1     2   3    4      5   6   7   8   9   ...   32   33   34  \
0         0  tcp  http  SF  215  45076   0   0   0   0  ...    0  0.0  0.0   
1         0  tcp  http  SF  162   4528   0   0   0   0  ...    1  1.0  0.0   
2         0  tcp  http  SF  236   1228   0   0   0   0  ...    2  1.0  0.0   
3         0  tcp  http  SF  233   2032   0   0   0   0  ...    3  1.0  0.0   
4         0  tcp  http  SF  239    486   0   0   0   0  ...    4  1.0  0.0   
...      ..  ...   ...  ..  ...    ...  ..  ..  ..  ..  ...  ...  ...  ...   
4898426   0  tcp  http  SF  212   2288   0   0   0   0  ...  255  1.0  0.0   
4898427   0  tcp  http  SF  219    236   0   0   0   0  ...  255  1.0  0.0   
4898428   0  tcp  http  SF  218   3610   0   0   0   0  ...  255  1.0  0.0   
4898429   0  tcp  http  SF  219   1234   0   0   0   0  ...  255  1.0  0.0   
4898430   0  tcp  http  SF  219   1098   0   0   0   0  ...  255  1.0  0.0   

           35    36   37    38   39   40       41  
0        0.00  0.00  0.0  0.00  0.0  0.0  normal.  
1        1.00  0.00  0.0  0.00  0.0  0.0  normal.  
2        0.50  0.00  0.0  0.00  0.0  0.0  normal.  
3        0.33  0.00  0.0  0.00  0.0  0.0  normal.  
4        0.25  0.00  0.0  0.00  0.0  0.0  normal.  
...       ...   ...  ...   ...  ...  ...      ...  
4898426  0.33  0.05  0.0  0.01  0.0  0.0  normal.  
4898427  0.25  0.05  0.0  0.01  0.0  0.0  normal.  
4898428  0.20  0.05  0.0  0.01  0.0  0.0  normal.  
4898429  0.17  0.05  0.0  0.01  0.0  0.0  normal.  
4898430  0.14  0.05  0.0  0.01  0.0  0.0  normal.  

[4898431 rows x 42 columns]

In [119]:
df = df.drop([1,2,3,41], axis = 1)
df

0    4      5   6   7   8   9   10  11  12  ...  31   32   33   34  \
0         0  215  45076   0   0   0   0   0   1   0  ...   0    0  0.0  0.0   
1         0  162   4528   0   0   0   0   0   1   0  ...   1    1  1.0  0.0   
2         0  236   1228   0   0   0   0   0   1   0  ...   2    2  1.0  0.0   
3         0  233   2032   0   0   0   0   0   1   0  ...   3    3  1.0  0.0   
4         0  239    486   0   0   0   0   0   1   0  ...   4    4  1.0  0.0   
...      ..  ...    ...  ..  ..  ..  ..  ..  ..  ..  ...  ..  ...  ...  ...   
4898426   0  212   2288   0   0   0   0   0   1   0  ...   3  255  1.0  0.0   
4898427   0  219    236   0   0   0   0   0   1   0  ...   4  255  1.0  0.0   
4898428   0  218   3610   0   0   0   0   0   1   0  ...   5  255  1.0  0.0   
4898429   0  219   1234   0   0   0   0   0   1   0  ...   6  255  1.0  0.0   
4898430   0  219   1098   0   0   0   0   0   1   0  ...   7  255  1.0  0.0   

           35    36   37    38   39   40  
0        0.00  0.00  0.0  0.00  0.0  0.0  
1        1.00  0.00  0.0  0.00  0.0  0.0  
2        0.50  0.00  0.0  0.00  0.0  0.0  
3        0.33  0.00  0.0  0.00  0.0  0.0  
4        0.25  0.00  0.0  0.00  0.0  0.0  
...       ...   ...  ...   ...  ...  ...  
4898426  0.33  0.05  0.0  0.01  0.0  0.0  
4898427  0.25  0.05  0.0  0.01  0.0  0.0  
4898428  0.20  0.05  0.0  0.01  0.0  0.0  
4898429  0.17  0.05  0.0  0.01  0.0  0.0  
4898430  0.14  0.05  0.0  0.01  0.0  0.0  

[4898431 rows x 38 columns]

In [120]:
arr = df.values
scaler = StandardScaler()
arr_scaled = scaler.fit_transform(arr)

In [121]:
kbins = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='uniform', subsample=None)
data_equi_width = kbins.fit_transform(arr_scaled)
data_categorical = pd.DataFrame(data_equi_width)
data_categorical

c:\Users\hnam\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_discretization.py:278: UserWarning: Feature 16 is constant and will be replaced with 0.
  warnings.warn(


0    1    2    3    4    5    6    7    8    9   ...   28   29   30  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  0.0   
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4898426  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898427  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898428  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898429  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898430  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   

          31   32   33   34   35   36   37  
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1        0.0  9.0  0.0  0.0  0.0  0.0  0.0  
2        0.0  4.0  0.0  0.0  0.0  0.0  0.0  
3        0.0  3.0  0.0  0.0  0.0  0.0  0.0  
4        0.0  2.0  0.0  0.0  0.0  0.0  0.0  
...      ...  ...  ...  ...  ...  ...  ...  
4898426  0.0  3.0  0.0  0.0  0.0  0.0  0.0  
4898427  0.0  2.0  0.0  0.0  0.0  0.0  0.0  
4898428  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
4898429  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
4898430  0.0  1.0  0.0  0.0  0.0  0.0  0.0  

[4898431 rows x 38 columns]

In [122]:
array = data_categorical.values

Tính độ đo tương đồng

$$S(x_i,y_i) = 
\begin{cases}
1 & \text{nếu } x_i = y_i \\
0 & \text{ngược lại}
\end{cases}
$$


In [123]:
def simple_similarity(X, Y):
    sim = 0
    for i in range(len(X)):
        if X[i] == Y[i]:
            sim += 1

    return sim /len(X)

Tính độ đo tần số suất hiện ngược

$$S(x_i,y_i) = 
\begin{cases}
\frac{1}{p_k(x)^2} & \text{nếu } x_i = y_i \\
0 & \text{ngược lại}
\end{cases}
$$
Với $p_k(x)$ là một tỉ số của các bản ghi mà thuộc tính thứ k lấy giá trị
x trong tập dữ liệu

In [124]:
# Tính pk 
def calculate_pk(array):
    pk_dict = {}
    num_rows, num_cols = array.shape
    
    for col_index in range(num_cols):
        col_values = array[:, col_index]
        unique_values, value_counts = np.unique(col_values, return_counts=True)
        
        column_ratio = {}
        for value, count in zip(unique_values, value_counts):
            column_ratio[value] = count / num_rows
        
        pk_dict[col_index] = column_ratio
    
    return pk_dict

# Độ đo tần suất xuất hiện ngược
# iof = inverse occurrence frequency
def iof_similarity(X, Y, pk_dict):
    sim = 0
    for i in range(len(X)):
        if X[i] == Y[i]:
            sim += 1 / pk_dict[i][X[i]] ** 2

    return sim /len(X)


Hàm tìm láng giếng gần

In [125]:
def find_nearest_neighbors(array, num_rows, similarity_measure):
    pk_dict = calculate_pk(array)
    neighbors = {}
    similarities = {}
    
    for i in range(num_rows):
        current_row = array[i]
        best_similarity = -1
        best_neighbor_index = -1
        
        for j in range(len(array)):
            if i == j:
                continue #Trùng hàng
            
            neighbor_row = array[j]
            
            if similarity_measure == 'simple':
                similarity = simple_similarity(current_row, neighbor_row)

            elif similarity_measure == 'iof':
                similarity = iof_similarity(current_row, neighbor_row, pk_dict)
                
            else:
                raise ValueError("'simple' or 'iof' only")
            
            if similarity > best_similarity:
                best_similarity = similarity
                best_neighbor_index = j
        
        neighbors[i] = best_neighbor_index
        similarities[i] = best_similarity
    
    return neighbors , similarities


Lưu kết quả ra df

In [126]:
def show_result(array, nrows, measures):
    neighbors, similarities = find_nearest_neighbors(array, nrows, measures)
    
    df = pd.DataFrame({'Row': range(nrows), 'Nearest Neighbor': neighbors.values(), 'Similarity Measure': similarities.values()})
    df = df.reset_index(drop=True)

    return df


Láng giềng gần bằng phương pháp `simple`

In [130]:
print('Láng giếng gần bằng độ đo tương đồng')
show_result(array[:100],100,'simple')

Láng giếng gần bằng độ đo tương đồng


Row  Nearest Neighbor  Similarity Measure
0     0                11            0.973684
1     1                 2            0.973684
2     2                 1            0.973684
3     3                 1            0.973684
4     4                 1            0.973684
..  ...               ...                 ...
95   95                85            1.000000
96   96                77            1.000000
97   97                77            1.000000
98   98                77            1.000000
99   99                77            1.000000

[100 rows x 3 columns]

Láng giếng gần bằng phương pháp `inverse occurrence frequency`

In [131]:
print('Láng giếng gần bằng độ đo tần số xuất hiện ngược')
show_result(array[:100],100,'iof')

Láng giếng gần bằng độ đo tần số xuất hiện ngược


Row  Nearest Neighbor  Similarity Measure
0     0                11            1.439652
1     1                64           11.522535
2     2                65           11.522535
3     3                66           11.522535
4     4                67           11.522535
..  ...               ...                 ...
95   95                85           12.019998
96   96                77            1.991145
97   97                77            1.991145
98   98                77            1.991145
99   99                77            1.991145

[100 rows x 3 columns]